### ISSUE TITLE
Need to typecast v-model as number

### ISSUE THREAD

**Issue by noahlocke** [kirschbaum-development/nova-inline-select#13]
@brandonferens When updating the `inline-select` field, I noticed that the `Toasted` message was always the same, no matter what I selected. More specifically, the select option of the field visibly changed to what I had selected, but the notification remained at whatever the value was when the page loaded. Even more strange was that everything else was working--meaning, the model was updated successfully. What I discovered was that when the page loads, Vue has the appropriate value for the field, which in my case is an integer (`status_id`). Yet when I selected a new select option, Vue updated the new `value` with a string. So `3` returned as `"3"`. I was able to fix this by changing `v-model="value"` to `v-model.number="value"` in the component. 

I'm not sure if this is the right way to approach this, I've never had this problem with Vue. I'm also not sure how we'd go about dynamically typecasting, as I'd imagine others will want to use string values as well as integers...

Any ideas?

**Comment by brandonferens** [comment]
@noahlocke I understand the issue. The PR you submitted #12 revealed this issue which is why I changed, in that PR, how lodash's `find()` method matches the value.

Adding `.number` to `v-model` makes sense, but only if we can guarantee that values will only ever be numbers, which we can't, like you said. I am personally using the package with string values.

I'm not sure the best way to approach this. Did you pull in the latest `v1.0.5` and test with that?

**Comment by noahlocke** [comment]
I'm just using strings instead ¯\_(ツ)_/¯
